name: Python CI with Appium and Android Emulator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: no
          emulator-locale: en_US
          emulator-options: -no-window -no-audio -no-boot-anim

      - name: Install System Image
        run: |
          echo "y" | sdkmanager --install "system-images;android-30;default;x86_64"

      - name: Create AVD
        run: |
          avdmanager create avd -n test -k "system-images;android-30;default;x86_64" --device "pixel"

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82 &

      - name: Wait for Emulator to Boot
        run: adb shell getprop init.svc.bootanim | grep -m 1 stopped

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium &

      - name: Run Appium Tests with Python
        run: python -m unittest discover -s tests/

      - name: Stop Android Emulator
        run: adb -s emulator-5554 emu kill

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/tests/test
